apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello-web
  name: hello-web
  namespace: default
spec:
  clusterIP: 10.15.240.242
  externalTrafficPolicy: Cluster
  ports:
    - nodePort: 31743
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: hello-web
  sessionAffinity: None
  type: LoadBalancer
