# Generated by Django 2.2.10 on 2020-03-03 04:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Restaurante', '0001_initial'),
        ('Salon', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Menu', '0001_initial'),
        ('Montaje', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cliente', models.ForeignKey(on_delete=True, related_name='Cliente', to=settings.AUTH_USER_MODEL)),
                ('Gerente', models.ForeignKey(on_delete=True, related_name='Gerente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato_Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cantidad', models.IntegerField(default=1)),
                ('Contrato', models.ForeignKey(on_delete=True, related_name='ContratoMenu', to='Contrato.Contrato')),
                ('Menu', models.ForeignKey(on_delete=True, related_name='MenuContrato', to='Menu.Menu')),
            ],
        ),
        migrations.AddField(
            model_name='contrato',
            name='Menu',
            field=models.ManyToManyField(through='Contrato.Contrato_Menu', to='Menu.Menu'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='Montaje',
            field=models.ForeignKey(on_delete=True, related_name='Montaje', to='Montaje.Montaje'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='Restaurante',
            field=models.ForeignKey(on_delete=True, related_name='Restaurante', to='Restaurante.Restaurante'),
        ),
        migrations.AddField(
            model_name='contrato',
            name='Salon',
            field=models.ForeignKey(on_delete=True, related_name='Salon', to='Salon.Salon'),
        ),
    ]
